In [1]:
import numpy as np

import psrk

┌ Warning: Replacing docs for `Roots.Roots :: Union{}` in module `Roots`
└ @ Base.Docs docs/Docs.jl:243


In [2]:
model = psrk.PSRK(
    [
        "octanoic acid",
        "hydrogen peroxide",
        "water",
        "diisopropyl ether",
        "peroctanoic acid",
    ]
)

z = np.array([0.0169607, 0.0240071, 0.1683388, 0.7858384, 0.0048550])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.000001, 0.3, 0.7, 0.000001, 0.000001]
y0 = [0.02, 0.00003, 0.00001, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(flash)

print(Q)

print(model.activity(101325, 303.15, flash[0])[1])
print(model.activity(101325, 303.15, flash[1])[1])

[[2.17174406e-05 1.82633376e-01 8.16951301e-01 3.64249845e-04
  2.93551508e-05]
 [1.94171317e-02 1.00367527e-03 7.42792961e-02 8.99745099e-01
  5.55479805e-03]]
3.364708069293469
[2.06437651e+03 1.00323173e+00 1.00101808e+00 2.50887156e+03
 1.15134093e+03]
[  2.30893908 182.55266789  11.00956882   1.0156833    6.08443123]


In [3]:
model = psrk.PSRK(
    [
        "octanoic acid",
        "hydrogen peroxide",
        "water",
        "toluene",
        "peroctanoic acid",
    ]
)

z = np.array([0.0129929, 0.0186183, 0.1349361, 0.8290296, 0.0044230])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.000001, 0.3, 0.7, 0.000001, 0.000001]
y0 = [0.02, 0.00003, 0.00001, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(Q)

print(flash)
print(actividades_x)
print(actividades_y)

2.363624154769142
[[1.50292941e-05 1.21706474e-01 8.78095226e-01 1.74151835e-04
  9.11872717e-06]
 [1.53044525e-02 2.56771925e-04 2.56847150e-03 9.76661126e-01
  5.20917813e-03]]
[0.04835532 0.12212038 0.87884611 0.97911764 0.01588174]
[0.04835532 0.12212038 0.87884611 0.97911764 0.01588174]


In [4]:
model = psrk.PSRK(
    [
        "octanoic acid",
        "hydrogen peroxide",
        "water",
        "hexane",
        "peroctanoic acid",
    ]
)

z = np.array([0.0190130, 0.0256777, 0.1562471, 0.7974415, 0.0016207])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.000001, 0.3, 0.7, 0.000001, 0.000001]
y0 = [0.02, 0.00003, 0.00001, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(Q)

print(flash)
print(actividades_x)
print(actividades_y)

2.1548575328809156
[[4.14198791e-05 1.42281535e-01 8.57546988e-01 1.02904390e-04
  2.71529862e-05]
 [2.31823466e-02 5.19063121e-05 2.12381385e-03 9.72671023e-01
  1.97091067e-03]]
[0.11445605 0.14281536 0.85826245 0.97667372 0.04104045]
[0.11445605 0.14281536 0.85826245 0.97667372 0.04104045]


In [5]:
model = psrk.PSRK(
    [
        "octanoic acid",
        "hydrogen peroxide",
        "water",
        "heptane",
        "peroctanoic acid",
    ]
)

z = np.array([0.0210732, 0.0283566, 0.1704566, 0.7786377, 0.0014759])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.000001, 0.3, 0.7, 0.000001, 0.000001]
y0 = [0.02, 0.00003, 0.00001, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(Q)

print(flash)
print(actividades_x)
print(actividades_y)

1.8844192718924986
[[4.17554188e-05 1.43602964e-01 8.56301332e-01 2.97617971e-05
  2.41874437e-05]
 [2.62391926e-02 4.84225798e-05 1.99129002e-03 9.69888608e-01
  1.83248684e-03]]
[0.11481396 0.14419288 0.85696561 0.97387155 0.0364043 ]
[0.11481396 0.14419288 0.85696561 0.97387155 0.0364043 ]


# Acetico

In [6]:
model = psrk.PSRK(
    [
        "acetic acid",
        "hydrogen peroxide",
        "water",
        "diisopropyl ether",
        "peracetic acid",
    ]
)

z = np.array([0.0195359228298132,	0.0264729672359217,	0.162886435988305,	0.789163679109803,	0.00194099483615746])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.01, 0.3, 0.7, 0.01, 0.01]
y0 = [0.02, 0.03, 0.01, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(Q)

print(flash)
print(actividades_x)
print(actividades_y)

1.6146320942627443
[[2.58065882e-02 1.92390280e-01 7.71379527e-01 6.59935219e-04
  9.76366908e-03]
 [1.85710484e-02 9.43081906e-04 6.92569132e-02 9.10491645e-01
  7.37311070e-04]]
[0.06263019 0.18717229 0.78114074 0.92165079 0.0242309 ]
[0.06263019 0.18717229 0.78114074 0.92165079 0.0242309 ]


In [7]:
model = psrk.PSRK(
    [
        "acetic acid",
        "hydrogen peroxide",
        "water",
        "toluene",
        "peracetic acid",
    ]
)

z = np.array([0.0140603062530234,	0.0195935942818186,	0.131447693284074,	0.831827789744339,	0.00307061643674482])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.01, 0.3, 0.7, 0.01, 0.01]
y0 = [0.02, 0.03, 0.01, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(Q)

print(flash)
print(actividades_x)
print(actividades_y)

2.73025688641855
[[2.60092794e-02 1.25378114e-01 8.37810402e-01 3.48977742e-04
  1.04532268e-02]
 [1.18734831e-02 2.33601359e-04 2.17379704e-03 9.83999619e-01
  1.71949924e-03]]
[0.06903899 0.12052176 0.84743687 0.98536714 0.02680749]
[0.06903899 0.12052176 0.84743687 0.98536714 0.02680749]


In [8]:
model = psrk.PSRK(
    [
        "acetic acid",
        "hydrogen peroxide",
        "water",
        "hexane",
        "peracetic acid",
    ]
)

z = np.array([0.0177465,	0.0234097,	0.1556298,	0.8005457,	0.0026682])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.01, 0.3, 0.7, 0.01, 0.01]
y0 = [0.02, 0.03, 0.01, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(actividades_x)
print(actividades_y)

print(Q)


[0.10605594 0.11720482 0.83488693 0.98755218 0.03061963]
[0.10605594 0.11720482 0.83488693 0.98755219 0.03061963]
2.0565874200394525


In [9]:
model = psrk.PSRK(
    [
        "acetic acid",
        "hydrogen peroxide",
        "water",
        "heptane",
        "peracetic acid",
    ]
)

z = np.array([0.019640,	0.021304,	0.174450,	0.782044,	0.002562])
sum_z = np.sum(z)
z = z / sum_z

x0 = [0.01, 0.3, 0.7, 0.01, 0.01]
y0 = [0.02, 0.03, 0.01, 0.8, 0.06]


flash = model.tp_flash(101325, 303.15, z, x0, y0)[0]

actividades_x = model.activity(101325, 303.15, flash[0])[0]
actividades_y = model.activity(101325, 303.15, flash[1])[0]


Q = (actividades_y[-1] * actividades_y[2]) / (
    actividades_y[0] * actividades_y[1]
)

print(Q)

print(flash)
print(actividades_x)
print(actividades_y)


2.118625637321329
[[4.48686725e-02 1.03146107e-01 8.40134622e-01 6.33797464e-05
  1.17872192e-02]
 [1.30798037e-02 2.26470386e-05 1.35243550e-03 9.85381942e-01
  1.63171892e-04]]
[0.11391375 0.09684311 0.85529902 0.98640975 0.02732632]
[0.11391375 0.09684311 0.85529902 0.98640975 0.02732632]
